# Generated by Django 2.0.2 on 2018-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='s_curriculum',
        ),
        migrations.AddField(
            model_name='students',
            name='s_curriculum',
            field=models.ManyToManyField(to='school.S_CURRICULUM'),
        ),
    ]
