# Generated by Django 2.0.2 on 2018-05-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20180517_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.ManyToManyField(to='school.Students')),
                ('project', models.ManyToManyField(to='school.S_CURRICULUM')),
            ],
        ),
    ]
