# Generated by Django 2.0.2 on 2018-05-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_unsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='s_photo',
            field=models.ImageField(upload_to='cover/'),
        ),
    ]
