# Generated by Django 2.0.2 on 2018-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20180524_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='unsign',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unsign',
            name='project',
        ),
        migrations.DeleteModel(
            name='Unsign',
        ),
    ]
