# Generated by Django 2.0.2 on 2018-05-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20180524_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='project',
        ),
    ]
