# Generated by Django 2.0.2 on 2018-05-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_sign_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
